name: NexusPermit
version: '${version}'

main: org.LuminolCraft.nexuspermit.NexusPermit
api-version: '1.20'
load: POSTWORLD

commands:
  v:
    description: 输入网站给出的验证码，完成 MC 账号绑定核验
    usage: /v <验证码>
